# Generated by Django 4.2.17 on 2025-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='titile',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='titile',
            new_name='title',
        ),
    ]
