# Generated by Django 4.2.17 on 2025-03-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_titile_file_title_rename_titile_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='title')),
                ('avatar', models.FileField(upload_to='mos/', verbose_name='avatar')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
