# Generated by Django 4.2.17 on 2025-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_catagries_product_catagories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='descreption',
            field=models.TextField(blank=True, verbose_name='descreption'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='descreption',
            field=models.TextField(blank=True, verbose_name='descreption'),
        ),
    ]
